const male = [
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
    {"first_name": "_f_", "last_name": "_L_", "username": "_u_", "character_name": "_c_"},
  ]


  const first = [
    // 60 American
    "Ethan", "Liam", "Noah", "Aiden", "Jackson", "Lucas", "Caden", "Mason", "Oliver", "Elijah",
    "Alexander", "Sebastian", "Mateo", "Diego", "Leo", "David", "Daniel", "Jayden", "Carter", "Henry",
    "Samuel", "Max", "Jack", "Benjamin", "Landon", "Adam", "Santiago", "Nathan", "Caleb", "Isaac",
    "Miguel", "Owen", "Evan", "Wyatt", "Andrew", "Gabriel", "Joshua", "Julian", "Anthony", "James",
    "Lincoln", "Dylan", "Christopher", "Logan", "Ryan", "Nicholas", "Nolan", "Eli", "Tyler", "Jaxon",
    "John", "Jace", "Levi", "Austin", "Pablo", "Jose", "Thomas", "Adrian", "Christian", "Ezra",
    // 10 spanish
    "Alejandro",
    "Mateo",
    "Lucas",
    "Daniel",
    "Adrián",
    "Carlos",
    "Javier",
    "Pablo",
    "Santiago",
    "Diego",
    // 5 Black
    "Malik",
    "Jamal",
    "Jalen",
    "Tyrone",
    "Darnell",
    // 8 Asian boy names
    "Ji-hoon",
    "Min-jae",
    "Seo-jun",
    "Hyun-woo",
    "Jin-ho",
    "Joon-hyuk",
    "Kyung-soo",
    "Sung-min",
    // 17 Indian
    "Aarav",
    "Aditya",
    "Arjun",
    "Aryan",
    "Ayush",
    "Dhruv",
    "Ishaan",
    "Kabir",
    "Rohan",
    "Rishi",
    "Shivansh",
    "Vivaan",
    "Vihaan",
    "Advait",
    "Yash",
    "Pranav",
    "Reyansh",
  ]
  